# Generated by Django 3.0.3 on 2020-02-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('prof', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('check_att', models.PositiveIntegerField(default=0)),
                ('lev_of_diff', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('grade', models.PositiveIntegerField(default=0)),
                ('achievement', models.PositiveIntegerField(default=0)),
                ('belongsto_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
    ]
